# src/custom_stats/config.yaml

custom_stats:

  - name: "status_counts"
    label: "Status Breakdown"
    type: "count_by_object"
    predicate: "http://w3id.org/sche/ma/status"
    chart:
      type: "bar"
      options:
        responsive: true
        plugins:
          legend:
            display: false
